### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by vibr77** [btb/LanguageCard#2]
Hello Bradley, 
Thanks for sharing your work, 

I have ordered 5x of this card and it is not so easy to find the memory chip, 
I replaced them by 2x AS7C164A-15PCN: SRAM SRAM SRAM, 64K, 8k x 8, 5v, 28pin Skinny P-DIP, 15ns

The pin setup seems to be the same, 

However the card is not working and freezing when it tries to use the additional 16K.

How can I investigate what is wrong, do you have an idea.

Thanks 

Vincent

**Comment by amazingcobrazil** [comment]
> Hello Bradley, Thanks for sharing your work,
> 
> I have ordered 5x of this card and it is not so easy to find the memory chip, I replaced them by 2x AS7C164A-15PCN: SRAM SRAM SRAM, 64K, 8k x 8, 5v, 28pin Skinny P-DIP, 15ns
> 
> The pin setup seems to be the same,
> 
> However the card is not working and freezing when it tries to use the additional 16K.
> 
> How can I investigate what is wrong, do you have an idea.
> 
> Thanks
> 
> Vincent

I also built some boards for my Apple IIs and I'm having exactly the same problem:  freezing when I try to access the other 16KB of the board in ProDOS, for example. I'm using Cy7C185 on my boards. Have you made any progress in the tests?

**Comment by vibr77** [comment]
Hello,
When I changed the Rom to a single rom chip (27C16) if I am not wrong it started working. I suspect that the legacy roms at too slow
V

From: amazingcobrazil ***@***.***>
Reply to: btb/LanguageCard ***@***.***>
Date: Friday 16 August 2024 at 00:06
To: btb/LanguageCard ***@***.***>
Cc: Vincent BESSON ***@***.***>, Author ***@***.***>
Subject: Re: [btb/LanguageCard] Freezing (Issue #2)


Hello Bradley, Thanks for sharing your work,

I have ordered 5x of this card and it is not so easy to find the memory chip, I replaced them by 2x AS7C164A-15PCN: SRAM SRAM SRAM, 64K, 8k x 8, 5v, 28pin Skinny P-DIP, 15ns

The pin setup seems to be the same,

However the card is not working and freezing when it tries to use the additional 16K.

How can I investigate what is wrong, do you have an idea.

Thanks

Vincent

I also built some boards for my Apple IIs and I'm having exactly the same problem: freezing when I try to access the other 16KB of the board in ProDOS, for example. I'm using Cy7C185 on my boards. Have you made any progress in the tests?

**Comment by vibr77** [comment]
I still have the issue, I will try with old narrow SRAM to see if it change something of not

**Comment by vibr77** [comment]
I change the SRAM by TC5588 and Cy7C185, it does not help, there is something else not working
Vincent

**Comment by vibr77** [comment]
Based on all the test I have made this card is working without any issue 👍 
- My Apple II ws having a bad DRAM chip causing freeze and data corruption,
- If you struggle to find SRAM for this card, you can use AS7C164A-15PCN it is working like a charm

I think we can close this issue

**Comment by btb** [comment]
I'm glad to hear it. My apologies that I didn't get around to helping you with this
